version: '2'

services:
  web:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./projects:/var/www/html
      - ./config:/etc/apache2/sites-available
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "6662:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql